name: CI Latest Release
on:
  pull_request:
    branches:
      - main

jobs:
  ci-latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Build a new release based on the code
        run: make release-test

      - name: Diff binaries
        run: diff -u ./release/latest/smtp-proxy-for-notify ./release/latest/smtp-proxy-for-notify-test || exit 1
